# Generated by Django 3.2.6 on 2025-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_rename_num_documento_paciente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationStats',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('simulated_errors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadísticas de Simulación',
                'verbose_name_plural': 'Estadísticas de Simulación',
            },
        ),
    ]
