# Generated by Django 3.2.6 on 2025-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_simulationstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationstats',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
