resources:
  # External HTTP access to voting coordinator
  - name: coordinator-firewall-web
    type: compute.v1.firewall
    properties:
      network: projects/arquisoft-sprint3/global/networks/default
      priority: 1000
      direction: INGRESS
      sourceRanges:
        - 0.0.0.0/0
      targetTags:
        - cbd-circuit-breaker
      allowed:
        - IPProtocol: TCP
          ports:
            - 8080

  # Internal traffic: coordinator -> diagnostic apps
  - name: allow-coordinator-to-diagnostics
    type: compute.v1.firewall
    properties:
      network: projects/arquisoft-sprint3/global/networks/default
      priority: 1000
      direction: INGRESS
      sourceTags:
        - cbd-circuit-breaker
      targetTags:
        - cbd-services-firewall
      allowed:
        - IPProtocol: TCP
          ports:
            - 8000

  # Router and NAT for egress of instances without external IP
  - name: cbd-router
    type: compute.v1.router
    properties:
      region: us-central1
      network: projects/arquisoft-sprint3/global/networks/default
      nats:
        - name: cbd-nat
          natIpAllocateOption: AUTO_ONLY
          sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES

  # Voting Coordinator instance with external IP
  - type: compute.v1.instance
    name: cbd-voting-coordinator-instance
    properties:
      zone: us-central1-a
      machineType: projects/arquisoft-sprint3/zones/us-central1-a/machineTypes/e2-micro
      disks:
        - boot: true
          autoDelete: true
          initializeParams:
            sourceImage: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
      networkInterfaces:
        - network: projects/arquisoft-sprint3/global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      tags:
        items:
          - cbd-circuit-breaker
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update
              sudo pip3 install -r /labs/ANG_DiagnosticAPP/requirements.txt
              cd /labs/ANG_DiagnosticAPP
              sudo python3 manage.py migrate
              sudo nohup python3 manage.py runserver 0.0.0.0:8080 &

  # Diagnostic app instances (no external IP)
  - type: compute.v1.instance
    name: cbd-diagnostic-app-a
    properties:
      zone: us-central1-a
      machineType: projects/arquisoft-sprint3/zones/us-central1-a/machineTypes/e2-micro
      disks:
        - boot: true
          autoDelete: true
          initializeParams:
            sourceImage: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
      networkInterfaces:
        - network: projects/arquisoft-sprint3/global/networks/default
          # no accessConfigs = no external IP
      tags:
        items:
          - cbd-services-firewall
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update
              sudo pip3 install -r /labs/ANG_DiagnosticAPP/requirements.txt
              cd /labs/ANG_DiagnosticAPP
              sudo python3 manage.py migrate
              sudo nohup python3 manage.py runserver 0.0.0.0:8000 &

  - type: compute.v1.instance
    name: cbd-diagnostic-app-b
    properties:
      zone: us-central1-a
      machineType: projects/arquisoft-sprint3/zones/us-central1-a/machineTypes/e2-micro
      disks:
        - boot: true
          autoDelete: true
          initializeParams:
            sourceImage: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
      networkInterfaces:
        - network: projects/arquisoft-sprint3/global/networks/default
      tags:
        items:
          - cbd-services-firewall
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update
              sudo pip3 install -r /labs/ANG_DiagnosticAPP/requirements.txt
              cd /labs/ANG_DiagnosticAPP
              sudo python3 manage.py migrate
              sudo nohup python3 manage.py runserver 0.0.0.0:8000 &

  - type: compute.v1.instance
    name: cbd-diagnostic-app-c
    properties:
      zone: us-central1-a
      machineType: projects/arquisoft-sprint3/zones/us-central1-a/machineTypes/e2-micro
      disks:
        - boot: true
          autoDelete: true
          initializeParams:
            sourceImage: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
      networkInterfaces:
        - network: projects/arquisoft-sprint3/global/networks/default
      tags:
        items:
          - cbd-services-firewall
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update
              sudo pip3 install -r /labs/ANG_DiagnosticAPP/requirements.txt
              cd /labs/ANG_DiagnosticAPP
              sudo python3 manage.py migrate
              sudo nohup python3 manage.py runserver 0.0.0.0:8000 &
