# Generated by Django 3.2.6 on 2025-03-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
