# Generated by Django 3.2.6 on 2025-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedSuspiciousAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento Sospechoso (Detectado)',
                'verbose_name_plural': 'Intentos Sospechosos (Detectados)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
