# Generated by Django 3.2.6 on 2025-03-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='infoAdmin',
            new_name='Medico',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='id',
            new_name='id_medico',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
