# Generated by Django 3.2.6 on 2025-03-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoAdmin', '0002_auto_20250313_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='id_medico',
            new_name='id',
        ),
    ]
